//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigSharpSQL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MigSharpSQL.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load migrations..
        /// </summary>
        internal static string CannotLoadMigrations {
            get {
                return ResourceManager.GetString("CannotLoadMigrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration script {0} is absent..
        /// </summary>
        internal static string MigrationScriptIsAbsent {
            get {
                return ResourceManager.GetString("MigrationScriptIsAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration processor {0} cannot be loaded..
        /// </summary>
        internal static string ProcessorCannotBeLoaded {
            get {
                return ResourceManager.GetString("ProcessorCannotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor is not supported..
        /// </summary>
        internal static string ProcessorIsNotSupported {
            get {
                return ResourceManager.GetString("ProcessorIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider name cannot be null..
        /// </summary>
        internal static string ProcessorNameCannotBeNull {
            get {
                return ResourceManager.GetString("ProcessorNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider {0} cannot be loaded..
        /// </summary>
        internal static string ProviderCannotBeLoaded {
            get {
                return ResourceManager.GetString("ProviderCannotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script {0} cannot be loaded..
        /// </summary>
        internal static string ScriptCannotBeLoaded {
            get {
                return ResourceManager.GetString("ScriptCannotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state {0} does not exist..
        /// </summary>
        internal static string StateDoesNotExists {
            get {
                return ResourceManager.GetString("StateDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are only {0} substate(s) available for state {1}, but database stays in {2} substate..
        /// </summary>
        internal static string SubstateIsNotApplicable {
            get {
                return ResourceManager.GetString("SubstateIsNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown database state {0}..
        /// </summary>
        internal static string UnknownDatabaseState {
            get {
                return ResourceManager.GetString("UnknownDatabaseState", resourceCulture);
            }
        }
    }
}
